// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	dbConnect: (profile: ConnectionProfile) => typedError<ConnectionInfo, AppError>(__TAURI_INVOKE("db_connect", { profile })),
	dbTestConnection: (profile: ConnectionProfile) => typedError<ConnectionInfo, AppError>(__TAURI_INVOKE("db_test_connection", { profile })),
	dbDisconnect: (connectionId: string) => __TAURI_INVOKE<void>("db_disconnect", { connectionId }),
	dbListActiveConnections: () => __TAURI_INVOKE<string[]>("db_list_active_connections"),
	dbSaveConnection: (profile: ConnectionProfile) => typedError<null, AppError>(__TAURI_INVOKE("db_save_connection", { profile })),
	dbListSavedConnections: () => typedError<SavedConnectionProfile[], AppError>(__TAURI_INVOKE("db_list_saved_connections")),
	dbConnectSaved: (connectionId: string) => typedError<ConnectionInfo, AppError>(__TAURI_INVOKE("db_connect_saved", { connectionId })),
	dbDeleteSavedConnection: (connectionId: string) => typedError<null, AppError>(__TAURI_INVOKE("db_delete_saved_connection", { connectionId })),
	dbRenameSavedConnection: (connectionId: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("db_rename_saved_connection", { connectionId, name })),
	/**
	 *  Opens the OS's native file picker for choosing an SSH private key
	 *  file. Returns `None` if the user cancels.
	 */
	sshPickKeyFile: () => typedError<string | null, AppError>(__TAURI_INVOKE("ssh_pick_key_file")),
	dbPickSqliteFile: () => typedError<string | null, AppError>(__TAURI_INVOKE("db_pick_sqlite_file")),
	dbPickDuckdbFile: () => typedError<string | null, AppError>(__TAURI_INVOKE("db_pick_duckdb_file")),
	dbListTables: (connectionId: string) => typedError<TableRef[], AppError>(__TAURI_INVOKE("db_list_tables", { connectionId })),
	dbGetTableColumns: (connectionId: string, schema: string, table: string) => typedError<ColumnInfo[], AppError>(__TAURI_INVOKE("db_get_table_columns", { connectionId, schema, table })),
	dbListIndexes: (connectionId: string, schema: string, table: string) => typedError<IndexInfo[], AppError>(__TAURI_INVOKE("db_list_indexes", { connectionId, schema, table })),
	dbListConstraints: (connectionId: string, schema: string, table: string) => typedError<ConstraintInfo[], AppError>(__TAURI_INVOKE("db_list_constraints", { connectionId, schema, table })),
	dbGetTableDdl: (connectionId: string, schema: string, table: string) => typedError<string, AppError>(__TAURI_INVOKE("db_get_table_ddl", { connectionId, schema, table })),
	dbRenderDdl: (connectionId: string, schema: string, statements: DdlStatement[]) => typedError<DdlPreview[], AppError>(__TAURI_INVOKE("db_render_ddl", { connectionId, schema, statements })),
	dbExecuteDdl: (connectionId: string, schema: string, statements: DdlStatement[]) => typedError<DdlBatchResult, AppError>(__TAURI_INVOKE("db_execute_ddl", { connectionId, schema, statements })),
	dbFetchTableRows: (connectionId: string, schema: string, table: string, limit: number, offset: number, filters: TableFilter[], sort: TableSort[]) => typedError<TableRowsResult, AppError>(__TAURI_INVOKE("db_fetch_table_rows", { connectionId, schema, table, limit, offset, filters, sort })),
	dbCountTableRows: (connectionId: string, schema: string, table: string, filters: TableFilter[]) => typedError<number, AppError>(__TAURI_INVOKE("db_count_table_rows", { connectionId, schema, table, filters })),
	dbUpdateJsonCell: (connectionId: string, schema: string, table: string, row: { [key in string]: string }, column: string, value: string) => typedError<null, AppError>(__TAURI_INVOKE("db_update_json_cell", { connectionId, schema, table, row, column, value })),
	dbUpdateCellText: (connectionId: string, schema: string, table: string, row: { [key in string]: string }, column: string, value: string | null) => typedError<null, AppError>(__TAURI_INVOKE("db_update_cell_text", { connectionId, schema, table, row, column, value })),
	dbDeleteRows: (connectionId: string, schema: string, table: string, rows: { [key in string]: string }[]) => typedError<number, AppError>(__TAURI_INVOKE("db_delete_rows", { connectionId, schema, table, rows })),
	dbInsertRow: (connectionId: string, schema: string, table: string, values: { [key in string]: string }) => typedError<null, AppError>(__TAURI_INVOKE("db_insert_row", { connectionId, schema, table, values })),
	dbExecuteQuery: (connectionId: string, sql: string, tabId: string | null) => typedError<QueryResult, AppError>(__TAURI_INVOKE("db_execute_query", { connectionId, sql, tabId })),
	dbFetchQueryResultPage: (connectionId: string, tabId: string, offset: number, limit: number) => typedError<QueryResultPage, AppError>(__TAURI_INVOKE("db_fetch_query_result_page", { connectionId, tabId, offset, limit })),
	dbClearQueryResultCache: (tabId: string) => __TAURI_INVOKE<void>("db_clear_query_result_cache", { tabId }),
	dbCancelQuery: (connectionId: string, tabId: string) => typedError<null, AppError>(__TAURI_INVOKE("db_cancel_query", { connectionId, tabId })),
	dbBeginTransaction: (connectionId: string, tabId: string) => typedError<null, AppError>(__TAURI_INVOKE("db_begin_transaction", { connectionId, tabId })),
	dbCommitTransaction: (connectionId: string, tabId: string) => typedError<null, AppError>(__TAURI_INVOKE("db_commit_transaction", { connectionId, tabId })),
	dbRollbackTransaction: (connectionId: string, tabId: string) => typedError<null, AppError>(__TAURI_INVOKE("db_rollback_transaction", { connectionId, tabId })),
	dbHasActiveTransaction: (connectionId: string, tabId: string) => __TAURI_INVOKE<boolean>("db_has_active_transaction", { connectionId, tabId }),
	dbSaveQuery: (query: SavedQuery) => typedError<null, AppError>(__TAURI_INVOKE("db_save_query", { query })),
	dbListSavedQueries: (connectionId: string) => typedError<SavedQuery[], AppError>(__TAURI_INVOKE("db_list_saved_queries", { connectionId })),
	dbDeleteSavedQuery: (queryId: string) => typedError<null, AppError>(__TAURI_INVOKE("db_delete_saved_query", { queryId })),
	dbListQueryHistory: (connectionId: string) => typedError<QueryHistoryEntry[], AppError>(__TAURI_INVOKE("db_list_query_history", { connectionId })),
	dbClearQueryHistory: (connectionId: string) => typedError<null, AppError>(__TAURI_INVOKE("db_clear_query_history", { connectionId })),
	/**
	 *  Returns the OS's Downloads folder (or the home directory as a
	 *  fallback) to prepopulate the export dialog's output directory field.
	 */
	exportDefaultDirectory: () => typedError<string, AppError>(__TAURI_INVOKE("export_default_directory")),
	/**
	 *  Opens the OS's native folder picker, defaulted to `initial_directory`
	 *  when given. Returns `None` if the user cancels.
	 */
	exportPickDirectory: (initialDirectory: string | null) => typedError<string | null, AppError>(__TAURI_INVOKE("export_pick_directory", { initialDirectory })),
	/**
	 *  Starts a background chunked export of a table's rows, streaming
	 *  directly from the database. Returns immediately with a job id; progress
	 *  arrives via `export:progress`/`export:done`/`export:error`/
	 *  `export:cancelled` events carrying that same job id.
	 */
	exportRunTable: (jobId: string, request: TableExportRequest) => typedError<null, AppError>(__TAURI_INVOKE("export_run_table", { jobId, request })),
	/**
	 *  Starts a background export of already-fetched rows (e.g. a query
	 *  result). No DB access — just writes what the frontend already has, in
	 *  chunks, off the main thread so the UI never blocks.
	 */
	exportRunRows: (jobId: string, request: RowsExportRequest) => typedError<null, AppError>(__TAURI_INVOKE("export_run_rows", { jobId, request })),
	/**
	 *  Starts a background chunked export of a query tab's full result,
	 *  re-running the SQL against the database with `LIMIT`/`OFFSET` per
	 *  chunk rather than exporting whatever page is currently loaded in the
	 *  results grid.
	 */
	exportRunQuery: (jobId: string, request: QueryExportRequest) => typedError<null, AppError>(__TAURI_INVOKE("export_run_query", { jobId, request })),
	exportCancel: (jobId: string) => __TAURI_INVOKE<void>("export_cancel", { jobId }),
};

/* Types */
export type AppError = string;

export type ColumnEdit = {
	currentName: string,
	column: NewColumn,
};

export type ColumnInfo = {
	name: string,
	dataType: string,
	isNullable: boolean,
	default: string | null,
	isPrimaryKey: boolean,
	ordinalPosition: number,
};

export type ConnectionInfo = {
	id: string,
	serverVersion: string,
};

export type ConnectionProfile = {
	id: string,
	name: string,
	engine: Engine,
	host: string,
	port: number,
	database: string,
	user: string,
	password: string,
	sslMode: SslMode,
	readOnly?: boolean,
	sshTunnel?: SshTunnelConfig | null,
};

export type ConstraintInfo = {
	name: string,
	kind: ConstraintKind,
	columns: string[],
	referencedTable: string | null,
	referencedColumns: string[],
	onUpdate: ForeignKeyAction | null,
	onDelete: ForeignKeyAction | null,
	checkExpression: string | null,
};

export type ConstraintKind = "primary-key" | "foreign-key" | "unique" | "check";

export type DdlBatchResult = {
	results: DdlExecutionResult[],
	rolledBack: boolean,
};

export type DdlExecutionResult = {
	sql: string,
	success: boolean,
	error: string | null,
};

export type DdlPreview = {
	sql: string,
};

export type DdlStatement = { op: "createTable"; table: string; columns: NewColumn[] } | { op: "renameTable"; table: string; newName: string } | { op: "dropTable"; table: string } | { op: "addColumn"; table: string; column: NewColumn } | { op: "dropColumn"; table: string; column: string } | { op: "alterColumn"; table: string; edit: ColumnEdit } | { op: "addIndex"; table: string; index: NewIndex } | { op: "dropIndex"; table: string; index: string } | { op: "addConstraint"; table: string; constraint: NewConstraint } | { op: "dropConstraint"; table: string; constraint: string };

export type Engine = "postgres" | "neon" | "cockroach-db" | "greengage-db" | "my-sql" | "maria-db" | "ti-db" | "sqlite" | "sql-server" | "star-rocks" | "click-house" | "duck-db";

export type ExportFormat = "csv" | "json" | "sql";

export type FilterOperator = "equals" | "not-equals" | "greater-than" | "greater-or-equals" | "less-than" | "less-or-equals" | "like" | "ilike" | "not-like" | "in" | "is-null" | "is-not-null";

export type ForeignKeyAction = "no-action" | "restrict" | "cascade" | "set-null" | "set-default";

export type IndexInfo = {
	name: string,
	columns: string[],
	isUnique: boolean,
	isPrimary: boolean,
};

export type NewColumn = {
	name: string,
	dataType: string,
	isNullable: boolean,
	default: string | null,
};

export type NewConstraint = {
	name: string,
	kind: ConstraintKind,
	columns: string[],
	referencedTable: string | null,
	referencedColumns: string[],
	onUpdate: ForeignKeyAction | null,
	onDelete: ForeignKeyAction | null,
	checkExpression: string | null,
};

export type NewIndex = {
	name: string,
	columns: string[],
	isUnique: boolean,
};

/**
 *  Exports the full result of a query tab's SQL, re-run in chunks
 *  straight from the database — never limited to whatever page happens
 *  to be loaded in the results grid. Mirrors how Beekeeper Studio's
 *  "Export to File" always re-runs the query rather than exporting the
 *  rendered grid (see `TabQueryEditor.vue`'s `submitQueryToFile`).
 */
export type QueryExportRequest = {
	connectionId: string,
	tabId: string,
	sql: string,
	directory: string,
	fileName: string,
	format: ExportFormat,
	prettyPrint: boolean,
	chunkSize: number,
	deleteOnAbort: boolean,
};

export type QueryHistoryEntry = {
	id: string,
	connectionId: string,
	sql: string,
	status: QueryHistoryStatus,
	errorMessage: string | null,
	rowCount: number | null,
	durationMs: number,
	ranAt: string,
};

export type QueryHistoryStatus = "success" | "error";

export type QueryResult = { kind: "rows"; columns: string[]; rows: string[][]; totalRowCount: number | null; durationMs: number } | { kind: "affected"; rowCount: number; durationMs: number };

export type QueryResultPage = {
	columns: string[],
	rows: string[][],
	totalRowCount: number,
};

export type RowsExportRequest = {
	columns: string[],
	/**
	 *  Each cell already JSON-encoded as a string, same convention as
	 *  every other row payload crossing the IPC boundary (see
	 *  `TableRowsResult`'s doc comment).
	 */
	rows: string[][],
	directory: string,
	fileName: string,
	format: ExportFormat,
	prettyPrint: boolean,
	deleteOnAbort: boolean,
};

export type SavedConnectionProfile = {
	id: string,
	name: string,
	engine?: Engine,
	host: string,
	port: number,
	database: string,
	user: string,
	sslMode: SslMode,
	readOnly?: boolean,
	sshTunnel?: SavedSshTunnelConfig | null,
};

export type SavedQuery = {
	id: string,
	connectionId: string,
	title: string,
	sql: string,
	createdAt: string,
	updatedAt: string,
};

export type SavedSshTunnelConfig = {
	host: string,
	port: number,
	username: string,
	authKind: SshAuthKind,
	/**
	 *  Only meaningful when `auth_kind` is `PrivateKey` — a file path is
	 *  not a secret, so unlike the passphrase it's fine to keep in the
	 *  plain connections store.
	 */
	keyPath: string | null,
};

export type SortDirection = "asc" | "desc";

export type SshAuth = { kind: "password"; password: string } | { kind: "privateKey"; keyPath: string; 
/**  Empty string means the key file is unencrypted. */
passphrase: string };

export type SshAuthKind = "password" | "private-key";

export type SshTunnelConfig = {
	host: string,
	port: number,
	username: string,
	auth: SshAuth,
};

export type SslMode = "disable" | "prefer" | "require" | "verify-ca" | "verify-full";

export type TableExportRequest = {
	connectionId: string,
	schema: string,
	table: string,
	/**
	 *  Empty means "whole table" — every row, filters ignored. Non-empty
	 *  means "filtered view" — the same filters currently applied in the
	 *  grid, re-run against the database rather than limited to whatever
	 *  page is loaded. Matches the two scopes Beekeeper Studio's table
	 *  export menu offers ("Export whole table" / "Export filtered
	 *  view") — see `TableTable.vue`'s `exportTable`/`exportFiltered`.
	 */
	filters: TableFilter[],
	sort: TableSort[],
	directory: string,
	fileName: string,
	format: ExportFormat,
	prettyPrint: boolean,
	chunkSize: number,
	deleteOnAbort: boolean,
};

export type TableFilter = {
	column: string,
	operator: FilterOperator,
	value: string | null,
};

export type TableRef = {
	schema: string,
	name: string,
	kind: string,
	estimatedRows: number | null,
};

export type TableRowsResult = {
	columns: string[],
	rows: string[][],
	rowCount: number,
	hasMore: boolean,
	durationMs: number,
};

export type TableSort = {
	column: string,
	direction: SortDirection,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

