// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	dbConnect: (profile: ConnectionProfile) => typedError<ConnectionInfo, AppError>(__TAURI_INVOKE("db_connect", { profile })),
	dbTestConnection: (profile: ConnectionProfile) => typedError<ConnectionInfo, AppError>(__TAURI_INVOKE("db_test_connection", { profile })),
	dbDisconnect: (connectionId: string) => __TAURI_INVOKE<void>("db_disconnect", { connectionId }),
	dbListActiveConnections: () => __TAURI_INVOKE<string[]>("db_list_active_connections"),
	dbListTables: (connectionId: string) => typedError<TableRef[], AppError>(__TAURI_INVOKE("db_list_tables", { connectionId })),
	dbGetTableColumns: (connectionId: string, schema: string, table: string) => typedError<ColumnInfo[], AppError>(__TAURI_INVOKE("db_get_table_columns", { connectionId, schema, table })),
	dbFetchTableRows: (connectionId: string, schema: string, table: string, limit: number, offset: number) => typedError<TableRowsResult, AppError>(__TAURI_INVOKE("db_fetch_table_rows", { connectionId, schema, table, limit, offset })),
	dbUpdateJsonCell: (connectionId: string, schema: string, table: string, row: { [key in string]: string }, column: string, value: string) => typedError<null, AppError>(__TAURI_INVOKE("db_update_json_cell", { connectionId, schema, table, row, column, value })),
	dbUpdateCellText: (connectionId: string, schema: string, table: string, row: { [key in string]: string }, column: string, value: string | null) => typedError<null, AppError>(__TAURI_INVOKE("db_update_cell_text", { connectionId, schema, table, row, column, value })),
	dbDeleteRows: (connectionId: string, schema: string, table: string, rows: { [key in string]: string }[]) => typedError<number, AppError>(__TAURI_INVOKE("db_delete_rows", { connectionId, schema, table, rows })),
	dbExecuteQuery: (connectionId: string, sql: string) => typedError<QueryResult, AppError>(__TAURI_INVOKE("db_execute_query", { connectionId, sql })),
};

/* Types */
export type AppError = string;

export type ColumnInfo = {
	name: string,
	dataType: string,
	isNullable: boolean,
	default: string | null,
	isPrimaryKey: boolean,
	ordinalPosition: number,
};

export type ConnectionInfo = {
	id: string,
	serverVersion: string,
};

export type ConnectionProfile = {
	id: string,
	name: string,
	host: string,
	port: number,
	database: string,
	user: string,
	password: string,
	sslMode: SslMode,
};

/**
 *  See `TableRowsResult`'s doc comment: each cell is a JSON-encoded
 *  string, not a structured value, working around specta's inability
 *  to export `serde_json::Value` without infinite recursion.
 */
export type QueryResult = { kind: "rows"; columns: string[]; rows: string[][]; rowCount: number; truncated: boolean; durationMs: number } | { kind: "affected"; rowCount: number; durationMs: number };

export type SslMode = "disable" | "prefer" | "require" | "verify-ca" | "verify-full";

export type TableRef = {
	schema: string,
	name: string,
	kind: string,
	estimatedRows: number | null,
};

/**
 *  Each cell is a JSON-encoded string (e.g. `"\"hello\""`, `"42"`,
 *  `"null"`) rather than a structured value. specta cannot export
 *  `serde_json::Value` without recursing infinitely on its own
 *  Array/Object variants (a known limitation, see
 *  infrastructure/postgres/executor.rs's `row_value_to_json`), so
 *  cells are encoded to strings on the Rust side and `JSON.parse`d
 *  uniformly on the frontend instead.
 */
export type TableRowsResult = {
	columns: string[],
	rows: string[][],
	rowCount: number,
	hasMore: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

