// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	dbConnect: (profile: ConnectionProfile) => typedError<ConnectionInfo, AppError>(__TAURI_INVOKE("db_connect", { profile })),
	dbTestConnection: (profile: ConnectionProfile) => typedError<ConnectionInfo, AppError>(__TAURI_INVOKE("db_test_connection", { profile })),
	dbDisconnect: (connectionId: string) => __TAURI_INVOKE<void>("db_disconnect", { connectionId }),
	dbListActiveConnections: () => __TAURI_INVOKE<string[]>("db_list_active_connections"),
	dbSaveConnection: (profile: ConnectionProfile) => typedError<null, AppError>(__TAURI_INVOKE("db_save_connection", { profile })),
	dbListSavedConnections: () => typedError<SavedConnectionProfile[], AppError>(__TAURI_INVOKE("db_list_saved_connections")),
	dbConnectSaved: (connectionId: string) => typedError<ConnectionInfo, AppError>(__TAURI_INVOKE("db_connect_saved", { connectionId })),
	dbDeleteSavedConnection: (connectionId: string) => typedError<null, AppError>(__TAURI_INVOKE("db_delete_saved_connection", { connectionId })),
	dbRenameSavedConnection: (connectionId: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("db_rename_saved_connection", { connectionId, name })),
	dbListTables: (connectionId: string) => typedError<TableRef[], AppError>(__TAURI_INVOKE("db_list_tables", { connectionId })),
	dbGetTableColumns: (connectionId: string, schema: string, table: string) => typedError<ColumnInfo[], AppError>(__TAURI_INVOKE("db_get_table_columns", { connectionId, schema, table })),
	dbListIndexes: (connectionId: string, schema: string, table: string) => typedError<IndexInfo[], AppError>(__TAURI_INVOKE("db_list_indexes", { connectionId, schema, table })),
	dbListConstraints: (connectionId: string, schema: string, table: string) => typedError<ConstraintInfo[], AppError>(__TAURI_INVOKE("db_list_constraints", { connectionId, schema, table })),
	dbGetTableDdl: (connectionId: string, schema: string, table: string) => typedError<string, AppError>(__TAURI_INVOKE("db_get_table_ddl", { connectionId, schema, table })),
	dbRenderDdl: (connectionId: string, schema: string, statements: DdlStatement[]) => typedError<DdlPreview[], AppError>(__TAURI_INVOKE("db_render_ddl", { connectionId, schema, statements })),
	dbExecuteDdl: (connectionId: string, schema: string, statements: DdlStatement[]) => typedError<DdlBatchResult, AppError>(__TAURI_INVOKE("db_execute_ddl", { connectionId, schema, statements })),
	dbFetchTableRows: (connectionId: string, schema: string, table: string, limit: number, offset: number, filters: TableFilter[], sort: TableSort[]) => typedError<TableRowsResult, AppError>(__TAURI_INVOKE("db_fetch_table_rows", { connectionId, schema, table, limit, offset, filters, sort })),
	dbCountTableRows: (connectionId: string, schema: string, table: string, filters: TableFilter[]) => typedError<number, AppError>(__TAURI_INVOKE("db_count_table_rows", { connectionId, schema, table, filters })),
	dbUpdateJsonCell: (connectionId: string, schema: string, table: string, row: { [key in string]: string }, column: string, value: string) => typedError<null, AppError>(__TAURI_INVOKE("db_update_json_cell", { connectionId, schema, table, row, column, value })),
	dbUpdateCellText: (connectionId: string, schema: string, table: string, row: { [key in string]: string }, column: string, value: string | null) => typedError<null, AppError>(__TAURI_INVOKE("db_update_cell_text", { connectionId, schema, table, row, column, value })),
	dbDeleteRows: (connectionId: string, schema: string, table: string, rows: { [key in string]: string }[]) => typedError<number, AppError>(__TAURI_INVOKE("db_delete_rows", { connectionId, schema, table, rows })),
	dbInsertRow: (connectionId: string, schema: string, table: string, values: { [key in string]: string }) => typedError<null, AppError>(__TAURI_INVOKE("db_insert_row", { connectionId, schema, table, values })),
	dbExecuteQuery: (connectionId: string, sql: string) => typedError<QueryResult, AppError>(__TAURI_INVOKE("db_execute_query", { connectionId, sql })),
	dbSaveQuery: (query: SavedQuery) => typedError<null, AppError>(__TAURI_INVOKE("db_save_query", { query })),
	dbListSavedQueries: (connectionId: string) => typedError<SavedQuery[], AppError>(__TAURI_INVOKE("db_list_saved_queries", { connectionId })),
	dbDeleteSavedQuery: (queryId: string) => typedError<null, AppError>(__TAURI_INVOKE("db_delete_saved_query", { queryId })),
	dbListQueryHistory: (connectionId: string) => typedError<QueryHistoryEntry[], AppError>(__TAURI_INVOKE("db_list_query_history", { connectionId })),
	dbClearQueryHistory: (connectionId: string) => typedError<null, AppError>(__TAURI_INVOKE("db_clear_query_history", { connectionId })),
	/**
	 *  Returns the OS's Downloads folder (or the home directory as a
	 *  fallback) to prepopulate the export dialog's output directory field.
	 */
	exportDefaultDirectory: () => typedError<string, AppError>(__TAURI_INVOKE("export_default_directory")),
	/**
	 *  Opens the OS's native folder picker, defaulted to `initial_directory`
	 *  when given. Returns `None` if the user cancels.
	 */
	exportPickDirectory: (initialDirectory: string | null) => typedError<string | null, AppError>(__TAURI_INVOKE("export_pick_directory", { initialDirectory })),
	/**
	 *  Starts a background chunked export of a table's rows, streaming
	 *  directly from the database. Returns immediately with a job id; progress
	 *  arrives via `export:progress`/`export:done`/`export:error`/
	 *  `export:cancelled` events carrying that same job id.
	 */
	exportRunTable: (jobId: string, request: TableExportRequest) => typedError<null, AppError>(__TAURI_INVOKE("export_run_table", { jobId, request })),
	/**
	 *  Starts a background export of already-fetched rows (e.g. a query
	 *  result). No DB access — just writes what the frontend already has, in
	 *  chunks, off the main thread so the UI never blocks.
	 */
	exportRunRows: (jobId: string, request: RowsExportRequest) => typedError<null, AppError>(__TAURI_INVOKE("export_run_rows", { jobId, request })),
	exportCancel: (jobId: string) => __TAURI_INVOKE<void>("export_cancel", { jobId }),
};

/* Types */
export type AppError = string;

/**
 *  An existing column's edited definition, as submitted from the
 *  frontend's inline column editor. `current_name` locates the column;
 *  `column` carries its full target shape (name, type, nullable,
 *  default) — MySQL's `MODIFY COLUMN` must restate the whole definition
 *  regardless of which fields actually changed, so this always carries
 *  all of them rather than a sparse patch.
 */
export type ColumnEdit = {
	currentName: string,
	column: NewColumn,
};

export type ColumnInfo = {
	name: string,
	dataType: string,
	isNullable: boolean,
	default: string | null,
	isPrimaryKey: boolean,
	ordinalPosition: number,
};

export type ConnectionInfo = {
	id: string,
	serverVersion: string,
};

export type ConnectionProfile = {
	id: string,
	name: string,
	engine: Engine,
	host: string,
	port: number,
	database: string,
	user: string,
	password: string,
	sslMode: SslMode,
};

export type ConstraintInfo = {
	name: string,
	kind: ConstraintKind,
	columns: string[],
	/**
	 *  Set only for `ForeignKey` — the referenced table and its columns,
	 *  positionally matched to `columns`.
	 */
	referencedTable: string | null,
	referencedColumns: string[],
	/**
	 *  Set only for `Check` — the constraint's boolean expression, as the
	 *  engine reports it back (already-normalized text, not necessarily
	 *  what the user originally typed).
	 */
	checkExpression: string | null,
};

export type ConstraintKind = "primary-key" | "foreign-key" | "unique" | "check";

/**
 *  The result of running a batch of `DdlStatement`s together.
 * 
 *  Postgres runs the whole batch inside one transaction: if any statement
 *  fails, every statement in the batch is rolled back and `rolled_back`
 *  is `true` — nothing in the batch is left applied.
 * 
 *  MySQL cannot offer this guarantee — every DDL statement there
 *  auto-commits immediately, so a failure can never undo earlier
 *  statements in the same batch no matter what the client does. On
 *  MySQL, execution simply stops at the first failure and `rolled_back`
 *  is always `false`; statements before the failure stay applied.
 */
export type DdlBatchResult = {
	results: DdlExecutionResult[],
	rolledBack: boolean,
};

/**  The result of running one `DdlStatement` within a batch. */
export type DdlExecutionResult = {
	sql: string,
	success: boolean,
	error: string | null,
};

/**
 *  One rendered statement plus the raw SQL that will run for it — what
 *  the frontend's DDL-preview step shows before the user confirms
 *  execution (see Phase-3 doc, "generate DDL, show it, let you
 *  review/edit it, then run it").
 */
export type DdlPreview = {
	sql: string,
};

/**
 *  One engine-agnostic schema-write operation. Each `DatabaseDriver`
 *  implementation renders these into its own DDL dialect (see
 *  `infrastructure/{postgres,mysql}/ddl.rs`) — the frontend and the
 *  `domain` layer never construct raw SQL strings for writes.
 */
export type DdlStatement = { op: "addColumn"; table: string; column: NewColumn } | { op: "dropColumn"; table: string; column: string } | { op: "alterColumn"; table: string; edit: ColumnEdit } | { op: "addIndex"; table: string; index: NewIndex } | { op: "dropIndex"; table: string; index: string } | { op: "addConstraint"; table: string; constraint: NewConstraint } | { op: "dropConstraint"; table: string; constraint: string };

/**
 *  Which `DatabaseDriver` a profile connects through. `Neon` is not a
 *  distinct wire protocol — it's Postgres with Neon-friendly defaults
 *  (see `connections/types.ts`'s draft builder) — so it maps to the same
 *  `PostgresDriver` as `Postgres` in `domain/connection/service.rs`.
 */
export type Engine = "postgres" | "neon" | "my-sql";

export type ExportFormat = "csv" | "json" | "sql";

export type FilterOperator = "equals" | "not-equals" | "greater-than" | "greater-or-equals" | "less-than" | "less-or-equals" | 
/**  Raw SQL `LIKE` pattern — the caller supplies its own `%`/`_` wildcards. */
"like" | 
/**
 *  Raw SQL case-insensitive `ILIKE` pattern (Postgres) / `LIKE` on a
 *  case-insensitive collation (MySQL) — same wildcard convention as `Like`.
 */
"ilike" | "not-like" | 
/**  `value` is a comma-separated list; matches if the column equals any of them. */
"in" | "is-null" | "is-not-null";

export type IndexInfo = {
	name: string,
	columns: string[],
	isUnique: boolean,
	isPrimary: boolean,
};

/**
 *  A new column's definition, as submitted from the frontend's "Add
 *  column" form. `data_type` is a raw engine-dialect type string (e.g.
 *  `text`, `varchar(255)`, `int8`) — not validated against a fixed enum,
 *  since the set of valid types differs per engine and this app doesn't
 *  maintain its own type catalog.
 */
export type NewColumn = {
	name: string,
	dataType: string,
	isNullable: boolean,
	default: string | null,
};

/**
 *  A new constraint's definition, as submitted from the frontend's "Add
 *  constraint" form. Which fields apply depends on `kind`, mirroring
 *  `ConstraintInfo`'s own shape (see its doc comments for which fields
 *  are set for which kind).
 */
export type NewConstraint = {
	name: string,
	kind: ConstraintKind,
	columns: string[],
	referencedTable: string | null,
	referencedColumns: string[],
	checkExpression: string | null,
};

/**
 *  A new index's definition, as submitted from the frontend's "Add
 *  index" form.
 */
export type NewIndex = {
	name: string,
	columns: string[],
	isUnique: boolean,
};

export type QueryHistoryEntry = {
	id: string,
	connectionId: string,
	sql: string,
	status: QueryHistoryStatus,
	errorMessage: string | null,
	rowCount: number | null,
	durationMs: number,
	ranAt: string,
};

export type QueryHistoryStatus = "success" | "error";

/**
 *  See `TableRowsResult`'s doc comment: each cell is a JSON-encoded
 *  string, not a structured value, working around specta's inability
 *  to export `serde_json::Value` without infinite recursion.
 */
export type QueryResult = { kind: "rows"; columns: string[]; rows: string[][]; rowCount: number; truncated: boolean; durationMs: number } | { kind: "affected"; rowCount: number; durationMs: number };

export type RowsExportRequest = {
	columns: string[],
	/**
	 *  Each cell already JSON-encoded as a string, same convention as
	 *  every other row payload crossing the IPC boundary (see
	 *  `TableRowsResult`'s doc comment).
	 */
	rows: string[][],
	directory: string,
	fileName: string,
	format: ExportFormat,
	prettyPrint: boolean,
	deleteOnAbort: boolean,
};

export type SavedConnectionProfile = {
	id: string,
	name: string,
	engine?: Engine,
	host: string,
	port: number,
	database: string,
	user: string,
	sslMode: SslMode,
};

export type SavedQuery = {
	id: string,
	connectionId: string,
	title: string,
	sql: string,
	createdAt: string,
	updatedAt: string,
};

export type SortDirection = "asc" | "desc";

export type SslMode = "disable" | "prefer" | "require" | "verify-ca" | "verify-full";

export type TableExportRequest = {
	connectionId: string,
	schema: string,
	table: string,
	directory: string,
	fileName: string,
	format: ExportFormat,
	prettyPrint: boolean,
	chunkSize: number,
	deleteOnAbort: boolean,
};

/**
 *  A single column filter applied as a WHERE clause in `fetch_table_rows`.
 *  `value` is ignored for `IsNull`/`IsNotNull`.
 */
export type TableFilter = {
	column: string,
	operator: FilterOperator,
	value: string | null,
};

export type TableRef = {
	schema: string,
	name: string,
	kind: string,
	estimatedRows: number | null,
};

/**
 *  Each cell is a JSON-encoded string (e.g. `"\"hello\""`, `"42"`,
 *  `"null"`) rather than a structured value. specta cannot export
 *  `serde_json::Value` without recursing infinitely on its own
 *  Array/Object variants (a known limitation, see
 *  infrastructure/postgres/executor.rs's `row_value_to_json`), so
 *  cells are encoded to strings on the Rust side and `JSON.parse`d
 *  uniformly on the frontend instead.
 */
export type TableRowsResult = {
	columns: string[],
	rows: string[][],
	rowCount: number,
	hasMore: boolean,
	durationMs: number,
};

/**
 *  One column/direction pair in the ordered list `fetch_table_rows`
 *  results are sorted by (applied left to right, like a SQL multi-column
 *  `ORDER BY`).
 */
export type TableSort = {
	column: string,
	direction: SortDirection,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

